// packages/vue/components/button/button.vue
<script setup lang="ts">
import _styles from 'cosmic-design/button.module.css';
import { ref } from 'vue';
    
const props = defineProps({
    styles: {
        type: Object,
        default: _styles,
    },
    size: {
        type: String,
        default: 'xs',
    },
    disabled: {
        type: Boolean,
        default: false,
    },
});
const state = ref(props.disabled? 'disabled': 'normal');
</script>
<template>
    <div :class="[styles.button, state, size]">
        <slot
            name="prefix"
            :class="[styles.prefix, size]"
        />
        <slot :class="[styles.label]" />
        <slot
            name="subfix"
            :class="[styles.subfix , size]"
        />
    </div>
</template>

// packages/svelte/button/index.svelte
<script lang="ts">
    import _styles from '@cosmic-design/ui/button.module.css';
    import type { State, Size } from '@cosmic-design/ui/button'; ;
    // import Icon from '../icon/icon.svelte';
    import { createEventDispatcher } from 'svelte';
    export let styles = _styles;
    export let size: Size = 'base';
    export let disabled : boolean = false;
    let state = disabled ? 'disabled': 'normal';

    const dispatch = createEventDispatcher();
    function click(event: Event) {
		dispatch('click', event);
	}
</script>

<div class="{styles.button} {state} {size} {$$props.class || ''}" on:click={click}>
    <!-- <Icon></Icon> -->
    {#if $$slots.prefix}
        <slot name='prefix' classes="{styles.prefix} {size}"></slot>
    {/if}
    <slot classes={styles.label}>Button</slot>
    {#if $$slots.subfix}
        <slot name='subfix' classes="{styles.subfix} {size}"></slot>
    {/if}
</div>
